eureka:
  server:
    username: eureka
    password: eureka
  client:
    service-url:
      defaultZone: http://${eureka.server.username}:${eureka.server.password}@localhost:8090/eureka/

spring:
  security:
    jwt:
      secret: asdf1234

  rabbitmq:
    username: root
    password: root
    virtual-host: /spring-config

wtf: true